"""Pydantic models for the aio-mrr library.

This package contains all Pydantic models for request/response data validation.
"""

from aio_mrr.models.account import (
    AccountInfo,
    AlgoPoolInfo,
    AlgoProfileInfo,
    BalanceInfo,
    CurrencyStatus,
    DepositCurrencyInfo,
    NotificationsInfo,
    Pool,
    PoolCreateBody,
    PoolCreateResponse,
    PoolProfileInfo,
    PoolTestBody,
    PoolTestResult,
    PoolTestResultItem,
    PriceInfo,
    Profile,
    ProfileCreateBody,
    ProfileCreateResponse,
    ProfileDeleteResponse,
    SettingsInfo,
    Transaction,
    TransactionsList,
    TransactionsQueryParams,
    WithdrawCurrencyInfo,
)
from aio_mrr.models.base import BaseMRRModel, MRRResponse, MRRResponseError
from aio_mrr.models.common import HashInfo, PoolInfo, ServerInfo
from aio_mrr.models.info import (
    AlgoInfo,
    CurrencyInfo,
    InfoAlgosQueryParams,
    ServersList,
)
from aio_mrr.models.info.response import (
    HashInfo as InfoHashInfo,
    PriceInfo as InfoPriceInfo,
    ServerInfo as InfoServerInfo,
)
from aio_mrr.models.pricing import (
    ConversionRates,
    MarketRates,
    PricingInfo,
)
from aio_mrr.models.rental import (
    GraphData,
    RentalCreateBody,
    RentalExtendBody,
    RentalInfo,
    RentalList,
    RentalListQueryParams,
    RentalLogEntry,
    RentalMessage,
    RentalPoolBody,
)
from aio_mrr.models.rig import (
    RigBatchBody,
    RigCreateBody,
    RigExtendBody,
    RigGraphData,
    RigHashInfo,
    RigInfo,
    RigList,
    RigPoolBody,
    RigPortInfo,
    RigPriceInfo,
    RigSearchParams,
    RigThreadInfo,
)
from aio_mrr.models.riggroup import (
    RigGroupCreateBody,
    RigGroupInfo,
    RigGroupList,
    RigGroupUpdateBody,
)

__all__ = [
    "AccountInfo",
    "AlgoInfo",
    "AlgoPoolInfo",
    "AlgoProfileInfo",
    "BalanceInfo",
    "BaseMRRModel",
    "ConversionRates",
    "CurrencyInfo",
    "CurrencyStatus",
    "DepositCurrencyInfo",
    "GraphData",
    "HashInfo",
    "InfoAlgosQueryParams",
    "InfoHashInfo",
    "InfoPriceInfo",
    "InfoServerInfo",
    "MRRResponse",
    "MRRResponseError",
    "MarketRates",
    "NotificationsInfo",
    "Pool",
    "PoolCreateBody",
    "PoolCreateResponse",
    "PoolInfo",
    "PoolProfileInfo",
    "PoolTestBody",
    "PoolTestResult",
    "PoolTestResultItem",
    "PriceInfo",
    "PricingInfo",
    "Profile",
    "ProfileCreateBody",
    "ProfileCreateResponse",
    "ProfileDeleteResponse",
    "RentalCreateBody",
    "RentalExtendBody",
    "RentalInfo",
    "RentalList",
    "RentalListQueryParams",
    "RentalLogEntry",
    "RentalMessage",
    "RentalPoolBody",
    "RigBatchBody",
    "RigCreateBody",
    "RigExtendBody",
    "RigGraphData",
    "RigGroupCreateBody",
    "RigGroupInfo",
    "RigGroupList",
    "RigGroupUpdateBody",
    "RigHashInfo",
    "RigInfo",
    "RigList",
    "RigPoolBody",
    "RigPortInfo",
    "RigPriceInfo",
    "RigSearchParams",
    "RigThreadInfo",
    "ServerInfo",
    "ServersList",
    "SettingsInfo",
    "Transaction",
    "TransactionsList",
    "TransactionsQueryParams",
    "WithdrawCurrencyInfo",
]
